name: myapp-Ci-Cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Bump version
      id: bump_version
      run: |
        POM_FILE="myapp/pom.xml"
        current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f $POM_FILE)
        IFS='.' read -r -a version_parts <<< "$current_version"
        version_parts[2]=$((version_parts[2] + 1))
        new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
        mvn versions:set -DnewVersion=$new_version -f $POM_FILE
        echo "New version: $new_version"
        echo "::set-output name=new_version::$new_version"

    - name: Push new version
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add myapp/pom.xml
        git commit -m "Bump version to ${{ steps.bump_version.outputs.new_version }}"
        git push origin main

    - name: Package
      run: mvn -B package -f myapp/pom.xml

    - name: Build Docker image
      id: build_image
      run: |
        DOCKERHUB_REPO="geniamali/myapp"
        docker build --file myapp/Dockerfile -t ${DOCKERHUB_REPO}:${{ steps.bump_version.outputs.new_version }} -t ${DOCKERHUB_REPO}:latest .
        echo "::set-output name=repo::${DOCKERHUB_REPO}"

    - name: DockerHub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push to Docker Hub
      run: |
        docker push ${{ steps.build_image.outputs.repo }}:latest
        docker push ${{ steps.build_image.outputs.repo }}:${{ steps.bump_version.outputs.new_version }}

    - name: Run Docker image
      run: |
        docker run -d ${{ steps.build_image.outputs.repo }}:latest
